In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('opensea_asset_data_with_limit=150.csv')

In [4]:
df[['cv_plotSize_desc','cv_OCdistance_desc','cv_buildHeight_desc','floor_elev_desc']] = df.description.str.split(",", expand=True)
df

,id,name,description,traits,asset_contract.address,asset_contract.asset_contract_type,asset_contract.created_date,asset_contract.name,asset_contract.description,collection.description,...,cv_plotSize_m_sq,cv_OCdistance_m,cv_buildHeight_m,cv_floor_elev_m,neighborhood_temp,neighborhood,cv_plotSize_desc,cv_OCdistance_desc,cv_buildHeight_desc,floor_elev_desc
0,22495503,3 Ash Lane,"84m² undefined title parcel on undefined, 6975...","[{'trait_type': 'suburb', 'value': 'West End',...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,84.0,6975.0,14.0,0.0,on undefined,NaN,84m² undefined title parcel on undefined,6975m from the origin,with a 14m build height,floor is at 0m elevation
1,22495502,2 Strawberry Trail,"54m² plot title parcel on Far Far Away, 6935m ...","[{'trait_type': 'depth', 'value': 11, 'display...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,54.0,6935.0,8.0,0.0,on Far Far Away,NaN,54m² plot title parcel on Far Far Away,6935m from the origin,with a 8m build height,floor is at 0m elevation
2,22495448,2 Dew Street,"233m² undefined title parcel on undefined, 698...","[{'trait_type': 'suburb', 'value': 'West End',...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,233.0,6984.0,8.0,0.0,on undefined,NaN,233m² undefined title parcel on undefined,6984m from the origin,with a 8m build height,floor is at 0m elevation
3,22495447,2 Sharktooth Street,"90m² plot title parcel on Far Far Away, 6995m ...","[{'trait_type': 'height', 'value': 9, 'display...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,90.0,6995.0,9.0,0.0,on Far Far Away,NaN,90m² plot title parcel on Far Far Away,6995m from the origin,with a 9m build height,floor is at 0m elevation
4,22495446,2 Ash Lane,"142m² plot title parcel on Far Far Away, 6958m...","[{'trait_type': 'width', 'value': 13, 'display...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,142.0,6958.0,9.0,0.0,on Far Far Away,NaN,142m² plot title parcel on Far Far Away,6958m from the origin,with a 9m build height,floor is at 0m elevation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,20943740,19 Wharehine,"183m² plot title parcel on Poneke, 990m from t...","[{'trait_type': 'height', 'value': 11, 'displa...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,183.0,990.0,11.0,0.0,on Poneke,NaN,183m² plot title parcel on Poneke,990m from the origin,with a 11m build height,floor is at 0m elevation
146,20943654,19 Paparimu,"119m² plot title parcel on Poneke, 995m from t...","[{'trait_type': 'width', 'value': 12, 'display...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,119.0,995.0,8.0,0.0,on Poneke,NaN,119m² plot title parcel on Poneke,995m from the origin,with a 8m build height,floor is at 0m elevation
147,20943652,31 Rāwhitiroa,"285m² plot title parcel on Poneke, 989m from t...","[{'trait_type': 'width', 'value': 13, 'display...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,285.0,989.0,11.0,0.0,on Poneke,NaN,285m² plot title parcel on Poneke,989m from the origin,with a 11m build height,floor is at 0m elevation
148,20943651,2 Waipū,"159m² plot title parcel on Poneke, 979m from t...","[{'trait_type': 'height', 'value': 10, 'displa...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,159.0,979.0,10.0,0.0,on Poneke,NaN,159m² plot title parcel on Poneke,979m from the origin,with a 10m build height,floor is at 0m elevation
149,20943650,11 Wharehine,"99m² plot title parcel on Poneke, 990m from th...","[{'trait_type': 'height', 'value': 8, 'display...",0x79986af15539de2db9a5086382daeda917a9cf0c,non-fungible,2018-06-11T19:08:44.720025,Cryptovoxels,A virtual world on the Ethereum blockchain. Bu...,A virtual world on the Ethereum blockchain. Bu...,...,99.0,990.0,8.0,0.0,on Poneke,NaN,99m² plot title parcel on Poneke,990m from the origin,with a 8m build height,floor is at 0m elevation

In [6]:
df['cv_plotSize_m_sq'] = df.cv_plotSize_desc.str.extract('(\d+)')
df['cv_OCdistance_m'] = df.cv_OCdistance_desc.str.extract('(\d+)')
df['cv_buildHeight_m'] = df.cv_buildHeight_desc.str.extract('(\d+)')
df[['cv_plotSize_m_sq','cv_OCdistance_m','cv_buildHeight_m']]

    cv_plotSize_m_sq cv_OCdistance_m cv_buildHeight_m
0                 84            6975               14
1                 54            6935                8
2                233            6984                8
3                 90            6995                9
4                142            6958                9
..               ...             ...              ...
145              183             990               11
146              119             995                8
147              285             989               11
148              159             979               10
149               99             990                8

[150 rows x 3 columns]

In [10]:
df["neighborhood_temp"]= df["cv_plotSize_desc"].str.replace("^.*(?=on )", "")
df["neighborhood_temp"]

0         on undefined
1      on Far Far Away
2         on undefined
3      on Far Far Away
4      on Far Far Away
            ...
145          on Poneke
146          on Poneke
147          on Poneke
148          on Poneke
149          on Poneke
Name: neighborhood_temp, Length: 150, dtype: object

## Extraction!

In [17]:
df["neighborhood"] = df['neighborhood_temp'].str.split("on ", expand=True)[1]

In [18]:
df["neighborhood"]

0         undefined
1      Far Far Away
2         undefined
3      Far Far Away
4      Far Far Away
           ...
145          Poneke
146          Poneke
147          Poneke
148          Poneke
149          Poneke
Name: neighborhood, Length: 150, dtype: object